name: fiveesrd
description: Umbrella package that re-exports the FiveEsrd models, client, and datastore.
version: 0.1.3
repository: https://github.com/undrdev/5eSRD-dart

environment:
  sdk: ^3.10.0

dependencies:
  fiveesrd_models: ^0.1.1
  fiveesrd_client: ^0.1.1
  fiveesrd_datastore: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
