name: fiveesrd_models
description: Shared data models for the FiveEsrd suite.
version: 0.1.1
publish_to: none
repository: https://github.com/undrdev/5eSRD-dart
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
  swagger_dart_code_generator: ^4.1.0
